language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: Ho8E03CPCnkr59obVv5vnrl9nhRiY6TLMlsgYmxPN14w/qHswDyRvItthRVbQ5qJ0RLTCvI/7NlCM2PLVqu8W2G9gSlP8lBL2WdGJT0XjL7JsAMDKcCYJF5CNb3ShI6ETYMy5fDT9vTm0l1a9zm5QoEJsai17cae6VV3HhtgFv5/GVv1aVSwNIgszIyYzNLNcdUdLQaV9hyCsyLP+6xZVRtCdFfBlvbb1h72vodNdlC6ALeixmr0p/ZYhhngOYI6vsXRLFzyGQNK59Q9YwUJ2D3B1tr/Eqf0aQb70FKYOswCHA/XZqTkDXgptHBTF4ZvRKDZIK8QPfC0bLW91/lpvqhUwDYr7eFbxVjoU7O1agqScSUfP4qf6ZlTGDisIHt13QnekefDC4iLMQr+B/AlFNEIEBhbFlbFlxS66uW6YsgiBalrv0aa61Llm4Bsj4YZ22bRPY7+XwFFGBe1JFx+ZNZUCKsfpC6unHHa/9IDwcUlEuAAUUeWNIxFhBa4/6JJMbIK2lpnOYiwNBeqS4eo9TB15mFaxg28/Vj5sSvshkoeuvBYX6Fu2cKAo+djHaoW7gn/cCggoPuhdniD7WqFmyAPFYmAb2qYR208eOmoZihcLYbvlt+YTDd2L0FHIdhQ1jmjVh++97XkzWbbMi8I7v3VpKRqIwtJKAXTczUZTWw=
